<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>ArchLinux Installation Guide on Encrypted SSD &middot; Dany Nativel</title>
    <meta name="generator" content="Hugo 0.16" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Dany Nativel">
    
      <meta name="description" content="">
    
    
    <link rel="icon" href="https://danynativel.com/favicon.ico">
    <link rel="apple-touch-icon" href="https://danynativel.com/apple-touch-icon.png" />
    <link rel="stylesheet" href="https://danynativel.com/css/style.css">
    <link rel="stylesheet" href="https://danynativel.com/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://danynativel.com/css/monokai.css">
    <link rel="stylesheet" href="https://danynativel.com/fancybox/jquery.fancybox.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>
    <meta property="og:title" content="ArchLinux Installation Guide on Encrypted SSD" />
<meta property="og:description" content="This tutorial will guide you for installing ArchLinux on a GPT partition while using GRUB2 on a BIOS enabled PC (see Wiki for EFI) and thus on a SSD media based upon LUKS (encryption) over LVM. It is not aimed to replace the official ArchLinux installation guide or Wiki. It is just a collection of notes gathered from the official sources. As a reminder the Installation Guide can now also be found on the USB flash drive under /root/install.txt.
" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://danynativel.com/2013/02/10/archlinux-installation-guide-on-encrypted-ssd" />


<meta property="og:updated_time" content="2013-02-10T00:00:00&#43;00:00"/>










    
    
<meta itemprop="name" content="ArchLinux Installation Guide on Encrypted SSD">
<meta itemprop="description" content="This tutorial will guide you for installing ArchLinux on a GPT partition while using GRUB2 on a BIOS enabled PC (see Wiki for EFI) and thus on a SSD media based upon LUKS (encryption) over LVM. It is not aimed to replace the official ArchLinux installation guide or Wiki. It is just a collection of notes gathered from the official sources. As a reminder the Installation Guide can now also be found on the USB flash drive under /root/install.txt.
">


<meta itemprop="dateModified" content="2013-02-10T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="6587">



<meta itemprop="keywords" content="computer,freediving,photography,videography,apple,archlinux,competition,dance,hacking,hardware,how-to,linux,music,photos,review,security,tips,unraid,videos," />

    

  <meta name="twitter:card" content="summary"/>



<meta name="twitter:title" content="ArchLinux Installation Guide on Encrypted SSD"/>
<meta name="twitter:description" content="This tutorial will guide you for installing ArchLinux on a GPT partition while using GRUB2 on a BIOS enabled PC (see Wiki for EFI) and thus on a SSD media based upon LUKS (encryption) over LVM. It is not aimed to replace the official ArchLinux installation guide or Wiki. It is just a collection of notes gathered from the official sources. As a reminder the Installation Guide can now also be found on the USB flash drive under /root/install.txt.
"/>
<meta name="twitter:site" content="@danynativel"/>


    

    
</head>
<body>
<div class="container">


<div id="container">
	<header id="header">
  <div id="header-main" class="header-inner">
    <div class="outer">
      <a href="https://danynativel.com/" id="logo">
          
          <i class="logo" style="background-image: url('https://danynativel.com/img/facevase.png')"></i>
          
          <span class="site-title">Dany Nativel</span>
      </a>
      <nav id="main-nav">
          
          
          <a class="main-nav-link" href="https://danynativel.com/">Home</a>
          
          
          
          
          
          

          

          
          
          
          
          <a class="main-nav-link" href="https://danynativel.com/tags/">Tags</a>
          
          
          
          <a class="main-nav-link" href="https://danynativel.com/categories/">Categories</a>
          
          
      </nav>
        <nav id="sub-nav">
          <div class="profile" id="profile-nav">
            <a id="profile-anchor" href="javascript:;"><img class="avatar" src="https://danynativel.com/img/dnativel.png"><i class="fa fa-caret-down"></i></a>
          </div>
        </nav>
        <div id="search-form-wrap">
          <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form">
              <input type="search" name="q" results="0" class="search-form-input" placeholder="Search">
              <button type="submit" class="search-form-submit">
              </button>
              <input type="hidden" name="q" value="site:https://danynativel.com/">
         </form>
        </div>
    </div>
  </div>
  <div id="main-nav-mobile" class="header-sub header-inner">
    <table class="menu outer">
      <tbody>
          <tr>
          
          
          <td><a class="main-nav-link" href="https://danynativel.com/">Home</a></td>
          
          
          
          
          
          

          

          
          
          
          
          <td><a class="main-nav-link" href="https://danynativel.com/tags/">Tags</a></td>
          
          
          
          <td><a class="main-nav-link" href="https://danynativel.com/categories/">Categories</a></td>
          
          
          <td>
          <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form">
          <input type="search" name="q" results="0" class="search-form-input" placeholder="Search">
          <input type="hidden" name="q" value="site:https://danynativel.com/">
          </form>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</header>

   	
   	<div class="outer">
   		
	    <aside id="profile">
  <div class="inner profile-inner">
    <div class="base-info profile-block">
      <img id="avatar" src="https://danynativel.com/img/dnativel.png">
      <h2 id="name">Dany Nativel</h2>
      <h3 id="title">Freediver - Photographer - Hacker</h3>
      <span id="location"><i class="fa fa-map-marker"></i>Toulon</span>
      
          <a id="follow" href="https://twitter.com/danynativel">
              Follow
          </a>
      
    </div>
    <div class="article-info profile-block">
      <div class="article-info-block">
        18
        <span>Posts</span>
      </div>
      <div class="article-info-block">
        
          15
        
        <span>
            Tags
        </span>
      </div>
    </div>
    <div class="contact-info profile-block">
      <table class="contact-list">
        <tr>
          





































<td><a href="//linkedin.com/in/danynativel" target="_blank" title="LinkedIn"><i class="fa fa-linkedin"></i></a></td>















<td><a href="//twitter.com/danynativel" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></td>



<td><a href="//keybase.io/danynativel" target="_blank" title="Keybase"><i class="fa fa-key"></i></a></td>



<td><a href="http://photos.danynativel.com/" target="_blank" title="Photos"><i class="fa fa-picture-o"></i></a></td>



<td><a href="mailto:dany@nativel.net" target="_blank" title="Email"><i class="fa fa-envelope"></i></a></td>



          <td><a href="" target="_blank" title="RSS"><i class="fa fa-rss"></i></a></td>
        </tr>
      </table>
    </div>
  </div>
</aside>

	    

	    
<section id="main">

    <article id="page-undefined" class="article article-type-page" itemscope="" itemprop="blogPost">
        <div class="article-inner">
            
                <img src="https://danynativel.com/top/archlinux.png" class="article-banner">
            

            <header class="article-header">
    <a href="https://danynativel.com/2013/02/10/archlinux-installation-guide-on-encrypted-ssd">
    <h1 class="article-title" itemprop="name">
        ArchLinux Installation Guide on Encrypted SSD
    </h1>
    </a>
    <div class="article-meta">
        <div class="article-date">
            <i class="fa fa-calendar"></i>
            <time datetime="2013-02-10 00:00:00 &#43;0000 UTC" itemprop="datePublished">2013-02-10</time>
	    
        </div>

        
        
            
            
            <div class="article-category">
                <i class="fa fa-folder"></i>
                
                <a class="article-category-link" href="https://danynativel.com/categories/computer">Computer</a>
                
                
            </div>
            
        

        
            
            
            <div class="article-category">
                <i class="fa fa-tags"></i>
                
                <a class="article-category-link" href="https://danynativel.com/tags/linux">Linux</a>
                &middot;
                
                <a class="article-category-link" href="https://danynativel.com/tags/how-to">How-To</a>
                &middot;
                
                <a class="article-category-link" href="https://danynativel.com/tags/archlinux">ArchLinux</a>
                
                
            </div>
            
        
    </div>
</header>

            <div class="article-entry" itemprop="articleBody">
                

<p>This tutorial will guide you for installing ArchLinux on a GPT partition while using GRUB2 on a BIOS enabled PC (see Wiki for EFI) and thus on a SSD media based upon LUKS (encryption) over LVM. It is not aimed to replace the official ArchLinux installation guide or Wiki. It is just a collection of notes gathered from the official sources. As a reminder the Installation Guide can now also be found on the USB flash drive under /root/install.txt.</p>

<p>Once you have installed your system please make sure to consult my <a href="http://danynativel.com/blog/2013/06/10/emergency-commands-for-encrypted-archlinux-installation/">emergency commands</a> for accessing your encrypted data with a LiveCD USB Flash drive and also perform seamless upgrades using LVM snapshots.</p>

<h2 id="prepare-ssd">Prepare SSD</h2>

<p>Fill new drive with Random data:
    # dd if=/dev/urandom of=/dev/sda
takes long</p>

<p>or install frandom from AUR</p>

<pre><code># dd if=/dev/frandom of=/dev/sda
</code></pre>

<p>faster but less random</p>

<h2 id="prepare-usb-stick">Prepare USB stick</h2>

<p>Based upon 2012.10.01 ISO image or later from <a href="http://www.archlinux.org/download">http://www.archlinux.org/download</a>.</p>

<pre><code># dd if=/dev/zero of=/dev/sdx  bs=1k count=1
# dd if=archlinux-xxxxx.iso of=/dev/sdx
</code></pre>

<p>Replace sdx by your thumbdrive reference.</p>

<h2 id="install-from-usb">Install from USB</h2>

<p>Boot &amp; select x86_64 (or i686 if you want to stay with i686 architecture, max. 3GB SRAM)</p>

<h2 id="change-keyboard-layout">Change keyboard layout</h2>

<pre><code># loadkeys fr
</code></pre>

<h2 id="get-ip-address">Get IP address</h2>

<p>2012.08.04 image automatically starts the network and get an IP address via DHCP so the following step is not required.</p>

<p>Assuming you are on ethernet with a DHCP server.</p>

<pre><code># dhcpcd
</code></pre>

<h2 id="manually-partition-hard-drives">Manually partition hard drives</h2>

<pre><code># gdisk /dev/sda
</code></pre>

<p>Remove old partitions then create the following partitions:</p>

<ul>
<li>2MB, type EF02 (BIOS partition). This is used by GRUB2/BIOS-GPT. (/dev/sda1)</li>
<li>100MB, type 8300 (Linux). This will store /boot (/dev/sda2)</li>
<li>2GB, type 8200 (swap). This is our dedicated swap partition (not part of lvm). (/dev/sda3)</li>
<li>Remaining space, type 8E00 (LVM). Store both / and /home. (/dev/sda4).</li>
</ul>

<p>Swap is not part of the LVM group because it will be encrypted with its own random key upon each reboot.</p>

<p>REBOOT here in order to be able to do the cryptsetup step.</p>

<h2 id="prepare-encrypted-luks-space">Prepare encrypted LUKS space</h2>

<p>We need to align, enable TRIM and use the right payload for SSD.</p>

<pre><code># cryptsetup -c aes-cbc-essiv:sha256 -y -s 128 -h sha512 --align-payload=8192 luksFormat /dev/sda4
# cryptsetup luksOpen --allow-discards /dev/sda4 enc-lvm
</code></pre>

<p>&ndash;allow-discards does not work with luksFormat only for mounting</p>

<h2 id="setup-lvm-space">Setup LVM space</h2>

<pre><code># lvm pvcreate --dataalignment 4M /dev/mapper/enc-lvm
# lvm vgcreate vgroup /dev/mapper/enc-lvm
# lvm lvcreate -L 4GB -n root vgroup    change size !!!!!
# !!! NO NO lvm lvcreate -L 512MB -n swap vgroup
# !!! NO ... We want to keep some free space for snapshots lvm lvcreate -l 100%FREE -n home vgroup
# lvm lvcreate -L 400GB -n home vgroup
</code></pre>

<p>-l 100%FREE</p>

<h2 id="configure-block-devices-filesystems-and-mountpoints">Configure block devices, filesystems, and mountpoints</h2>

<h3 id="format-boot-root-and-home">Format /boot, /root and /home</h3>

<p>Format and enable TRIM support.</p>

<pre><code># mkfs.ext2 /dev/sda2
# mkfs.ext4 -E discard /dev/mapper/vgroup-root
# mkfs.ext4 -E discard /dev/mapper/vgroup-home
</code></pre>

<h3 id="get-5-space-from-home-partition">Get 5% space from /home partition</h3>

<p>5% space are by default hidden on ext4 partitions. This is typically used on root partition as a safeguard when the disk gets full.
On non-root partition this hidden space can be easily and safely reclaimed back by using the following command.</p>

<pre><code># tune2fs -m 0 /dev/mapper/vgroup-home
</code></pre>

<h3 id="mount-the-partitions">Mount the partitions</h3>

<pre><code># mount /dev/mapper/vgroup-root /mnt
# mkdir /mnt/boot
# mount /dev/sda2 /mnt/boot
# mkdir /mnt/home
# mount /dev/mapper/vgroup-home /mnt/home
</code></pre>

<h2 id="select-installation-mirror">Select installation mirror</h2>

<p>ftp.archlinux.org is throttled to 50KB/s.</p>

<p>Before installing, you may want to edit /etc/pacman.d/mirrorlist such that your preferred mirror is first. This copy of the mirrorlist will be installed on your new system by pacstrap as well, so it&rsquo;s worth getting it right.</p>

<h2 id="install-the-base-system">Install the base system</h2>

<pre><code># pacstrap /mnt base base-devel
</code></pre>

<h2 id="install-a-bootloader">Install a bootloader</h2>

<p>Folllowing will install GRUB2. If you want EFI please refer to Wiki.</p>

<pre><code># pacstrap /mnt grub-bios
</code></pre>

<h2 id="generate-fstab">Generate fstab</h2>

<p>Generate an fstab file with the following command. UUIDs will be used because they have certain advantages (see fstab#Identifying filesystems). If you would prefer to use labels instead, replace the -U option with -L.
Note: If you encounter errors running genfstab or later in the install process, do not run genfstab again; just edit the fstab file.</p>

<pre><code># genfstab -U -p /mnt &gt;&gt; /mnt/etc/fstab
</code></pre>

<h3 id="mount-flags">Mount Flags</h3>

<p>Edit /mnt/etc/fstab to add TRIM support</p>

<pre><code>tmpfs       /tmp    tmpfs   nodev,nosuid    0   0
/dev/mapper/vgroup-home /home ext4 defaults,noatime,discard 0 2
/dev/mapper/vgroup-root / ext4 defaults,noatime,discard 0 1
/dev/sda2 /boot ext2 defaults,noatime 0 2
</code></pre>

<h2 id="chroot-into-our-newly-installed-system">Chroot into our newly installed system</h2>

<pre><code># arch-chroot /mnt
</code></pre>

<h2 id="configure-system">Configure system</h2>

<h3 id="root-password">Root password</h3>

<p>Set a root password with:</p>

<pre><code># passwd
</code></pre>

<h3 id="hostname">Hostname</h3>

<p>Add your hostname in /etc/hostname.</p>

<pre><code>myhostname
</code></pre>

<p>Set it to your liking. This is the name of your computer.</p>

<p>Add also your hostname in /etc/hosts, coinciding with the one specified in /etc/hostname as an alias, so that it looks like this:</p>

<pre><code>127.0.0.1   localhost.localdomain   localhost myhostname
::1         localhost.localdomain   localhost myhostname
</code></pre>

<p>Note: ::1 is the IPv6 equivalent of 127.0.0.1</p>

<h3 id="console-fonts-and-keymap">Console fonts and keymap</h3>

<p>Set keymap and font name in /etc/vconsole.conf.</p>

<pre><code>KEYMAP=fr
FONT=
FONT_MAP=
</code></pre>

<p>KEYMAP
        The available keymaps are in /usr/share/kbd/keymaps. Please note that this setting is only valid for your TTYs, not any graphical window managers or X.
FONT
        Available alternate console fonts reside in /usr/share/kbd/consolefonts/. The default (blank) is safe.
FONT_MAP
        Defines the console map to load with the setfont program at boot. Possible maps are found in /usr/share/kbd/consoletrans, if needed. The default (blank) is safe.</p>

<h3 id="timezone">Timezone</h3>

<p>Edit the file /etc/timezone and write your Zone/Subzone. Available time zones and subzones can be found in the /usr/share/zoneinfo/<Zone>/<SubZone> directories. Example:</p>

<pre><code>Europe/Paris
</code></pre>

<p>Additionaly, create a symbolic link /etc/localtime to the same /usr/share/zoneinfo/<Zone>/<SubZone> using this command:</p>

<pre><code># ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
</code></pre>

<h3 id="locale">Locale</h3>

<h4 id="enable-locales">Enable locales</h4>

<p>Edit /etc/locale.gen and uncomment:</p>

<pre><code>en_US.UTF-8 UTF-8
fr_FR.UTF-8 UTF-8
fr_FR ISO-8859-15
fr_FR@euro ISO-8859-15
</code></pre>

<h4 id="generate-locales">Generate locales</h4>

<pre><code># locale-gen
</code></pre>

<h4 id="setting-up-system-wide-locale">Setting up system-wide locale</h4>

<p>Add your language to /etc/locale.conf.</p>

<pre><code>LANG=fr_FR.UTF-8
LC_COLLATE=&quot;fr_FR.UTF-8&quot;
</code></pre>

<h4 id="export-current-language-for-initramfs-creation">Export current language for initramfs creation</h4>

<p>We will be adding keymap to mkinicpio.conf therefore we need to environment variable LANG.</p>

<pre><code># export LANG=fr_FR.UTF-8
</code></pre>

<h3 id="hardware-clock-time">Hardware clock time</h3>

<p>When using UTC launch the following command:</p>

<pre><code># hwclock --systohc --utc
</code></pre>

<h2 id="configure-the-network">Configure the network</h2>

<p>If not using DHCP or network manager, please see wiki for rc.conf configuration.</p>

<h3 id="prepare-initramfs-build">Prepare initramfs build</h3>

<p>Add keymap to kernel for non-US keyboard on boot.</p>

<p>Edit /etc/mkinitcpio.conf and insert &ldquo;keymap&rdquo; after &ldquo;sata&rdquo; (no quote required).</p>

<p>add keymap, encrypt and lvm2 before filesystems</p>

<pre><code>OLD: HOOKS=&quot;base udev autodetect modconf block filesystems keyboard fsck&quot;
    NOW: HOOKS=&quot;base udev autodetect modconf block keymap encrypt lvm2 filesystems usbinput fsck&quot;
</code></pre>

<h3 id="create-an-initial-ramdisk-environment">Create an initial ramdisk environment</h3>

<pre><code># mkinitcpio -p linux
</code></pre>

<h3 id="configure-the-bootloader">Configure the bootloader</h3>

<h4 id="install-grub2-to-hard-drive">Install GRUB2 to hard-drive</h4>

<pre><code># grub-install /dev/sda
</code></pre>

<p>To prevent a (harmless) error message at boot time execute:</p>

<pre><code># cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
</code></pre>

<h4 id="add-ssd-trim-and-encryption-support">Add SSD TRIM and encryption support</h4>

<p>nano /etc/default/grub</p>

<pre><code>GRUB_CMDLINE_LINUX=&quot;cryptdevice=/dev/sda4:vgroup:allow-discards&quot;
</code></pre>

<p>No need to specify the root=/dev/mapper&hellip; is added automatically.</p>

<h4 id="generate-grub2-configuration">Generate GRUB2 configuration #####</h4>

<pre><code># grub-mkconfig -o /boot/grub/grub.cfg
</code></pre>

<h2 id="unmount-the-partitions">Unmount the partitions</h2>

<p>If you are still in the chroot environment then type exit or Ctrl+D in order to exit chroot. Since the partitions are mounted under /mnt, we use the following command to unmount them.</p>

<pre><code># exit
# umount /mnt/boot
# umount /mnt/home
# umount /mnt
</code></pre>

<h2 id="reboot">Reboot</h2>

<p>Execute the following command and remove the installation media.</p>

<pre><code># reboot
</code></pre>

<h2 id="enable-encrypted-swap">Enable encrypted swap</h2>

<h3 id="setup-encrypted-swap-with-random-key">Setup encrypted Swap with random key</h3>

<pre><code> # mkswap /dev/sda3 &amp;&amp; swapon /dev/sda3
</code></pre>

<p>If swap has been set before:</p>

<pre><code># dd if=/dev/urandom of=/dev/sda3
</code></pre>

<p>Edit /etc/crypttab</p>

<pre><code>enc-swap       /dev/sda3    /dev/urandom        cipher=aes-cbc-essiv:sha256,size=128,hash=sha512,swap
</code></pre>

<p>Edit /etc/fstab</p>

<pre><code>#/dev/sda2 swap swap defaults 0 0
/dev/mapper/enc-swap swap swap defaults 0 0
</code></pre>

<h3 id="change-swap-space-behavior">Change swap space behavior</h3>

<p>One can place a swap partition on an SSD. Note that most modern desktops with an excess of 2 Gigs of memory rarely use swap at all. The notable exception is systems which make use of the hibernate feature. The following is recommended tweak for SSDs using a swap partition that will reduce the &ldquo;swappiness&rdquo; of the system thus avoiding writes to swap.</p>

<p>/etc/sysctl.d/99-sysctl.conf</p>

<pre><code>vm.swappiness=1
vm.vfs_cache_pressure=50
</code></pre>

<p>Reboot</p>

<p>Check</p>

<pre><code># cat /proc/sys/vm/swappiness
</code></pre>

<h2 id="change-i-o-scheduler-for-ssd">Change I/O scheduler for SSD</h2>

<p>benchmark scheduler
<a href="http://ubuntuforums.org/showthread.php?t=1464706">http://ubuntuforums.org/showthread.php?t=1464706</a></p>

<p>To do this, create and edit a file in /etc/udev/rules.d named something like &lsquo;60-schedulers.rules&rsquo;. In the file include the following:</p>

<pre><code># set deadline scheduler for non-rotating disks
ACTION==&quot;add|change&quot;, KERNEL==&quot;sd[a-z]&quot;, TEST!=&quot;queue/rotational&quot;, ATTR{queue/scheduler}=&quot;deadline&quot;
ACTION==&quot;add|change&quot;, KERNEL==&quot;sd[a-z]&quot;, ATTR{queue/rotational}==&quot;0&quot;, ATTR{queue/scheduler}=&quot;deadline&quot;

# set cfq scheduler for rotating disks
ACTION==&quot;add|change&quot;, KERNEL==&quot;sd[a-z]&quot;, ATTR{queue/rotational}==&quot;1&quot;, ATTR{queue/scheduler}=&quot;cfq&quot;
</code></pre>

<p>Of course, set deadline/cfq to the desired schedulers. Changes should occur upon next boot. To check success of the new rule:</p>

<pre><code># cat /sys/block/sdX/queue/scheduler   #where X is the device in question
</code></pre>

<p>Note: Keep in mind cfq is the default scheduler, so the second rule with the standard kernel is not actually necessary. Also, in the example sixty is chosen because that is the number udev uses for its own persistent naming rules. Thus, it would seem that block devices are at this point able to be modified and this is a safe position for this particular rule. But the rule can be named anything so long as it ends in &lsquo;.rules&rsquo;. (Credit: falconindy and w0ng for posting on his blog)</p>

<h2 id="add-additional-repositories">Add additional repositories</h2>

<p>Most people will want to use [core], [extra] and [community].</p>

<h3 id="multilib">Multilib</h3>

<p>If you installed Arch Linux x86_64, it&rsquo;s recommended that you enable the [multilib] repository, as well (to be able to run both 32 bit and 64 bit applications):</p>

<pre><code>[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
</code></pre>

<p>yaourt + multilib + other repos</p>

<h3 id="archlinuxfr">archlinuxfr</h3>

<p>Required for installing yaourt &amp; virtualbox and many other packages</p>

<p>Add as root the following into /etc/pacman.conf:</p>

<p>For 32-bit (i686) installations:</p>

<pre><code>[archlinuxfr]
SigLevel = Optional TrustAll
Server = http://repo.archlinux.fr/i686
</code></pre>

<p>For 64-bit installations:</p>

<pre><code>[archlinuxfr]
SigLevel = Optional TrustAll
Server = http://repo.archlinux.fr/x86_64
</code></pre>

<p>Refresh software list with:</p>

<pre><code># pacman -Syy
</code></pre>

<h3 id="package-management-with-yaourt-rather-than-pacman">Package management with Yaourt rather than pacman</h3>

<p>Add nice colors when browsing packages</p>

<pre><code># pacman -S yaourt pacman-color colordiff
</code></pre>

<p>Search both binary repo but also AUR</p>

<pre><code># yaourt mc
</code></pre>

<p>Complete update and upgrade, even for packages coming from AUR</p>

<pre><code># yaourt -Syu --aur
</code></pre>

<h2 id="add-default-user">Add default user</h2>

<pre><code># useradd -m -g users -s /bin/bash archie
</code></pre>

<p>Setup password for new user:</p>

<pre><code># passwd archie
</code></pre>

<p>None of these groups is needed for standard desktop permissions like sound, 3D, printing, mounting, etc. as long as the logind (or consolekit) session isn&rsquo;t broken (for example by starting X on a different VT than where you logged in).</p>

<p>user groups
audio, camera, disk, floppy, games, locate, lp, network, networkmanager, optical, power, scanner, storage, sys, uucp, video, wheel  ???</p>

<p>system groups
adm, avahi, bin, clamav, daemon, dbus, ftp, gdm, hal, http, kmem, log, mail, mem, mpd, nobody, ntp, policykit, root, smmsp, tty, users
vboxsf, fuse</p>

<p>software groups
adbusers, cdemu, kvm, thinkpad, vboxusers, vmware, ssh, wireshark</p>

<h2 id="configure-sound">Configure sound</h2>

<p>Install the alsa-utils package:</p>

<pre><code># pacman -S alsa-utils
</code></pre>

<p>Also, you may want to install the alsa-oss package, which wraps applications written for OSS in a compatibility library, allowing them to work with ALSA. To install the alsa-oss package:</p>

<pre><code># pacman -S alsa-oss
</code></pre>

<p>As normal, non-root user, invoke /usr/bin/alsamixer:</p>

<pre><code># su - yourusername 
# alsamixer
</code></pre>

<p>Unmute the Master and PCM channels by scrolling to them with cursor left/right and pressing M. Increase the volume levels with the cursor-up key. (70-90 Should be a safe range.) Some machines, (like the Thinkpad T61), have a Speaker channel which must be unmuted and adjusted as well. Leave alsamixer by pressing ESC.</p>

<p>Ensure your speakers are properly connected, and test your sound configuration as normal user using :</p>

<pre><code># speaker-test -c 2
</code></pre>

<p>You should hear a very eloquent woman say, &ldquo;Front, center.&rdquo;</p>

<p>FOLLOWING&hellip; NOT SURE !!!
Exit your normal user shell and run /usr/sbin/alsactl as root to save settings:</p>

<pre><code># exit
# alsactl store
</code></pre>

<p>Not sure about the following one&hellip; doens&rsquo;t save anything.
This will create the file &lsquo;/etc/asound.state&rsquo;, saving the alsamixer settings.</p>

<h2 id="install-xorg">Install Xorg</h2>

<h3 id="core-xorg-install">Core Xorg install</h3>

<pre><code># pacman -S xorg-server xorg-xinit xorg-server-utils
</code></pre>

<p>The 3D utilities glxgears and glxinfo are included in the mesa package:</p>

<pre><code># pacman -S mesa
</code></pre>

<h3 id="video-driver">Video driver</h3>

<p>Then you need to install a suitable driver for your graphic card. You need to know its brand and model then consult main Archlinux wiki to see which driver better fits your needs. The output of the command:</p>

<pre><code># lspci | grep VGA
</code></pre>

<p>should help you to identify your card.</p>

<p>For a complete list of open-source video drivers, search the package database:</p>

<pre><code># pacman -Ss xf86-video | less
</code></pre>

<p>The following is for an Intel based graphic card.</p>

<pre><code># pacman -S xf86-video-intel lib32-intel-dri
</code></pre>

<h3 id="keyboard-mouse">Keyboard &amp; mouse</h3>

<p>Udev should be capable of detecting your hardware without problems. The evdev driver (xf86-input-evdev) is the modern hot-plugging input driver for almost all devices, so in most cases, installing input drivers is not needed.</p>

<p>Laptop users will also need the synaptics package to allow X to configure the touchpad:</p>

<pre><code># pacman -S xf86-input-synaptics
</code></pre>

<p>Set the keyboard layout (if you do not use a standard US keyboard).
To change your keyboard layout, edit /etc/X11/xorg.conf.d/10-evdev.conf</p>

<p>and add a XkbLayout line so it looks like:</p>

<pre><code>Section &quot;InputClass&quot;
        Identifier &quot;evdev keyboard catchall&quot;
        MatchIsKeyboard &quot;on&quot;
        MatchDevicePath &quot;/dev/input/event*&quot;
        Option  &quot;XkbLayout&quot; &quot;fr&quot;
        Option  &quot;XkbVariant&quot; &quot;latin9&quot;
        Driver &quot;evdev&quot;
EndSection
</code></pre>

<p>The XkbLayout key may differ from the keymap code you used with the loadkeys command. A list of many keyboard layouts and variants can be found in /usr/share/X11/xkb/rules/base.lst (after the line beginning with ! layout). For instance, the layout gb corresponds to &ldquo;English (UK)&rdquo;, whereas for the console it was loadkeys uk.</p>

<h3 id="test-x">Test X</h3>

<p>Install the default environment:</p>

<pre><code># pacman -S xorg-twm xorg-xclock xterm
</code></pre>

<p>Start X</p>

<pre><code># startx
</code></pre>

<h2 id="install-fonts">Install fonts</h2>

<p>At this point, you may wish to save time by installing visually pleasing, true type fonts, before installing a desktop environment/window manager. Dejavu and bitstream-vera are good, general-purpose font sets. You may also want to have the Microsoft font sets, which are especially popular on websites.</p>

<p>Install with:</p>

<pre><code># pacman -S ttf-dejavu ttf-bitstream-vera
# yaourt ttf-ms-fonts 
</code></pre>

<p>Allocine is missing one font that needs to be added manually!</p>

<h2 id="install-gnome">Install Gnome</h2>

<h3 id="base-system">Base system</h3>

<pre><code># pacman -S gnome gnome-extra
</code></pre>

<p>Remove tracker to enable old-fashion search in nautilus/nemo.</p>

<h3 id="gdm">GDM</h3>

<p>GDM is part of gnome-extra.</p>

<p>To make GDM the default graphical login method for the system, use the packaged systemd service file, gdm.service. Simply run the following command once to bring up GDM on boot:</p>

<pre><code># systemctl enable gdm
</code></pre>

<p>Starting GNOME manually</p>

<p>If you prefer to start GNOME manually from the console, add the following line to your ~/.xinitrc file:</p>

<p>~/.xinitrc</p>

<pre><code>exec gnome-session
</code></pre>

<p>You can get .xinitrc template from /etc/skel/.xinitc</p>

<h3 id="enable-gnome-networkmanager">Enable Gnome NetworkManager</h3>

<pre><code># systemctl enable NetworkManager
</code></pre>

<h3 id="gnome-tweak-tool">GNOME tweak tool</h3>

<p>This graphical tool customizes fonts, themes, titlebar buttons and other settings.</p>

<pre><code># pacman -S gnome-tweak-tool
</code></pre>

<h2 id="sudo">Sudo</h2>

<pre><code># pacman -S sudo
</code></pre>

<p>Configure for a given user:</p>

<pre><code># visudo
</code></pre>

<p>and add:</p>

<pre><code>alpha   ALL=(ALL) ALL
</code></pre>

<h2 id="guake">Guake</h2>

<pre><code># pacman -S guake
</code></pre>

<p>Guake autostart, add an entry to gnome-session</p>

<h2 id="zsh">zsh</h2>

<pre><code># pacman -S zsh grml-zsh-config
# yaourt oh-my-zsh-git
</code></pre>

<p>There is a conflict with /etc/skel/.zshrc, just rename it before installing oh-my-zsh-git</p>

<p>Change the default shell for the current user:</p>

<pre><code># chsh -s $(which zsh)
</code></pre>

<h2 id="enable-autologin">Enable autologin</h2>

<p>You can have GDM to directly log into your sessions without promptint for any password (safe since the whole disk is encrypted).</p>

<p>Edit /etc/gdm/custom.conf</p>

<pre><code> # GDM configuration storage
 [daemon]
 AutomaticLogin=alpha
 AutomaticLoginEnable=True
</code></pre>

<h2 id="enable-predicatable-network-interface-name">Enable predicatable network interface name</h2>

<p>For motherboards that have integrated NICs, it is important to have fixed device name. Many configuration problems are caused by interface name changing.</p>

<p>Udev is responsible for which device gets which name. Systemd v197 introduced Predictable Network Interface Names, which automatically assigns static names to network devices. Interfaces are now prefixed with en (ethernet), wl (WLAN), or ww (WWAN) followed by an automatically generated identifier, creating an entry such as enp0s25.</p>

<p>This behavior may be disabled by adding a symlink:</p>

<pre><code># sudo ln -s /dev/null /etc/udev/rules.d/80-net-name-slot.rules
</code></pre>

<h2 id="check-if-ssd-trim-is-working">Check if SSD TRIM is working</h2>

<p><a href="https://sites.google.com/site/lightrush/random-1/checkiftrimonext4isenabledandworking">https://sites.google.com/site/lightrush/random-1/checkiftrimonext4isenabledandworking</a></p>

<p><a href="http://worldsmostsecret.blogspot.fr/2012/04/how-to-activate-trim-on-luks-encrypted.html">http://worldsmostsecret.blogspot.fr/2012/04/how-to-activate-trim-on-luks-encrypted.html</a></p>

<p>sudo dmsetup table /dev/mapper/vgroup &ndash;showkeys</p>

<h2 id="virtualbox">VirtualBox</h2>

<pre><code># sudo pacman -S virtualbox virtualbox-guest-iso virtualbox-host-source linux-headers
# yaourt virtualbox-ext-oracle
</code></pre>

<p>virtualbox-modules can be used if not using custom kernel</p>

<p>Add the desired username to the vboxusers group. Everything may work fine without this step but shared folders and possibly some other optional stuff require it to work. The new group does not automatically apply to existing sessions; the user has to log in again.</p>

<pre><code># gpasswd -a username vboxusers
</code></pre>

<p>Load module on boot</p>

<p>Edit /etc/modules-load.d/virtualbox.conf and add:</p>

<pre><code>vboxdrv
</code></pre>

<h2 id="frequency-scaling">Frequency scaling</h2>

<p>Normally the CPU frequency driver should be loaded automatically.</p>

<p>For example for Intel:</p>

<pre><code># lsmod | grep acpi_cpufreq 
</code></pre>

<p>If not
To load the driver automatically at start-up, add a file specifying the appropriate driver to the /etc/modules-load.d/ directory. For example:</p>

<p>/etc/modules-load.d/cpufreq.conf</p>

<p>Install cpupower to monitor it:</p>

<pre><code># pacman -S cpupower
</code></pre>

<p>Change governor on boot</p>

<p>/etc/modules-load.d/cpufreq_gov.conf</p>

<pre><code># Load cpufreq governors
cpufreq_powersave
cpufreq_userspace
</code></pre>

<p>cpupower includes a daemon which allows users to set the desired scaling governor and min/max clock speeds for all processor cores at boot-time.</p>

<p>Before starting the daemon, edit /etc/conf.d/cpupower as root, selecting the desired governor and setting the min/max speed for your CPU(s).
Note: The exact min/max values of the CPU(s) can be determined by running cpupower frequency-info. However, these values are optional. Users may omit them entirely by deleting or commenting out the min/max_freq lines; scaling will work automatically.</p>

<p>With the appropriate configuration, start the daemon with the following command:</p>

<pre><code># systemctl start cpupower
</code></pre>

<p>To start the daemon automatically at startup:</p>

<pre><code># systemctl enable cpupower
</code></pre>

<p>threshold can be tweaked for better performance:
<a href="https://wiki.archlinux.org/index.php/Cpupower">https://wiki.archlinux.org/index.php/Cpupower</a></p>

<h2 id="mplayer">Mplayer</h2>

<pre><code>mplayer2, smplayer, vlc
</code></pre>

<p>codecs:</p>

<pre><code># pacman -S gstreamer0.10-plugins
</code></pre>

<h2 id="java">Java</h2>

<pre><code># pacman -S jre7-openjdk jre7-openjdk-headless icedtea-web-java7
</code></pre>

<h2 id="flash">Flash</h2>

<pre><code># pacman -S flashplugin
</code></pre>

<p>Flash Player: Bad (choppy) sound on the 64-bit version</p>

<p>There is a problem with Flash plugin 11 on 64-bit systems and a new memcpy routine in glibc (for more details see this Fefora bug report), which makes the sound choppy on MP3 streams. Current workarounds are:</p>

<pre><code>replacing the memcpy routine as suggested in this thread.
installing flashplugin-square from the AUR (this is a version of the Flash plugin with working hardware acceleration). 
</code></pre>

<h2 id="ntfs">NTFS</h2>

<pre><code># pacman -S ntfs-3g ntfsprogs
</code></pre>

<h2 id="gimp">GIMP</h2>

<pre><code># pacman -S gimp-devel
# pacman -S gimp-dbp gimp-plugin-gmic gimp-plugin-fblur gimp-plugin-lqr gimp-plugin-wavelet-decompose gimp-plugin-wavelet-denoise gimp-refocus gimp-ufraw
</code></pre>

<p>Yaourt for:
- gimp-fix-ca  (erro)
- gimp-plugin-image-reg (error)
- *gimp-plugin-saveforweb
- *gimp-plugin-separate+
- *gimp-plugin-wavelet-sharpen
- *gimp-resynth-heal-selection
- *gimpfx-foundry</p>

<h2 id="pdf-reader">PDF reader</h2>

<pre><code>evince, mupdf, acroread
</code></pre>

<p>Firefox pdf</p>

<p>External PDF viewers</p>

<p>To use an external PDF viewer you need #MozPlugger or #kpartsplugin.</p>

<p>If you want to use MozPlugger with Evince, for example, you have to find the lines containing pdf in the /etc/mozpluggerrc file and modify the corresponding line after GV() as below:</p>

<p>repeat noisy swallow(evince) fill: evince &ldquo;$file&rdquo;</p>

<p>(replace evince with something else if it is not your viewer of choice).</p>

<p>acroread + firefox</p>

<p>Be advised that the Firefox plugin cannot be used directly with this binary &ndash; it will not load in the 64-bit browser. To load it install the nspluginwrapper plackage from the official [multilib] repository and run:</p>

<p>$ nspluginwrapper -v -a -i</p>

<p>as a normal user. This checks the plugin directory and links the plugins as needed.</p>

<h2 id="ntp">NTP</h2>

<pre><code># pacman ntpd
# sytstemctl enable ntpd
</code></pre>

<h2 id="file-change-detection">File change detection</h2>

<p>Is it required?  Installed by samba. No longer required by gnome or Nautilus.</p>

<pre><code># pacman -S gamin
</code></pre>

<h2 id="go">GO</h2>

<pre><code>mkdir ~/go
export GOPATH=~/go
go get website.com/user/module
</code></pre>

<h2 id="mozplugger">mozplugger</h2>

<p>==&gt; You may need to delete your local
==&gt; ~/.mozilla/firefox/<profile-dir>/pluginreg.dat file for mozplugger to be
==&gt; enabled correctly after you update it. (It will get regenerated).
==&gt; To add more helpers, edit /etc/mozpluggerrc.
==&gt; The window name can be obtained using the utility xprop(1x).
==&gt; Type xprop WM_CLASS and click on a window.
yaourt mozplu  4,88s user 1,68s system 3% cpu 3:25,71 total</p>

<h2 id="cups">CUPS</h2>

<p>cups cups-filters cups-pdf system-config-printer-gnome</p>

<p>sudo pacman -S foomatic-db foomatic-db-engine foomatic-db-nonfree foomatic-filters</p>

<ul>
<li>explaing PDF setup
To use cups-pdf, restart cups and visit the cups
web interface at <a href="http://localhost:631/">http://localhost:631/</a></li>
</ul>

<p>You can now add a &ldquo;Virtual Printer (PDF Printer)&rdquo;
and use the Postscript/Generic postscript color
printer driver.</p>

<p>Note that cups-pdf has a configuration
file in /etc/cups. The default location for
pdf output is /var/spool/cups-pdf/$username.</p>

<h2 id="fingerprint">Fingerprint</h2>

<p>Please make sure your user is a member of &ldquo;plugdev&rdquo; group if you use UPEK
non-free library, and modify your PAM configuration
(e.g., /etc/pam.d/{login,su,sudo,gdm}).</p>

<p>fingerprint-polkit-agent conflicts with files in /etc/xdg/autostart that must
be removed:
 &ldquo;polkit-gnome-authentication-agent-1.desktop&rdquo; and
 &ldquo;polkit-kde-authentication-agent-1.desktop&rdquo;.</p>

<p>Add &ldquo;debug&rdquo; switch to fingerprint-gui, you can see the debug log in
/var/log/auth.log</p>

<p>Refer to &ldquo;Manual_en.html&rdquo; and &ldquo;CHANGELOG&rdquo; for more information.
Dépendances optionnelles pour fingerprint-gui
    libusb: for libbsapi
yaourt fingerprint  134,43s user 10,13s system 53% cpu 4:31,06 total</p>

<h2 id="digikam">Digikam</h2>

<ul>
<li>kipi + require for video thumbnails? + gtk theme manager!!</li>
</ul>

<h2 id="disable-pc-speaker-sound">Disable pc speaker sound</h2>

<p>créer le fichier /etc/modprobe.d/blacklist.conf avec pour contenu :</p>

<p>blacklist pcspkr</p>

<p>Cette petite ligne permet de désactiver le « beep » atroce et faisant saigner les oreilles sortant parfois des entrailles de la machine – pour un dispositif nomade, donc coutumier des salles de cours, c’est un comportement indisposant.</p>

<h2 id="intel-audio">Intel Audio</h2>

<p>DO NOT USE</p>

<p>créer le fichier /etc/modprobe.d/snd_hda_intel.conf avec le contenu :</p>

<pre><code>options snd-hda-intel model=laptop
options snd_hda_intel power_save=1
options snd-hda-intel enable_msi=1
</code></pre>

<h2 id="ck-kernel">CK kernel</h2>

<pre><code>ajouter le répertoire à /etc/pacman.conf

[repo-ck]
SigLevel = PackageRequired
Server = http://repo-ck.com/$arch

ajouter la signature de graysky

# pacman-key -r 5EE46C4C
# pacman-key --lsign-key 5EE46C4C

mettre à jour la base de pacman (et avoir la musique en tête, accessoirement, de rien c’est gratuit)

# pacman -Syy

installer le noyau qui va bien (ici optimisé pour un Intel Atom)

# pacman -S linux-ck-corex linux-ck-corex-headers
</code></pre>

<p>If using SSD you might want to stick to deadline schedule as mentioned earlier.</p>

<p>If using HDD you might want ot use CK bfq scheduler.
Append &ldquo;elevator=bfq&rdquo; to the kernel boot line in /boot/grub/menu.lst if using grub or in /etc/default/grub under the GRUB_CMDLINE_LINUX_DEFAULT=&ldquo;quiet&rdquo; line followed by rebuilding /boot/grub/grub.cfg via the standard &ldquo;grub-mkconfig -o /boot/grub/grub.cfg&rdquo; command.</p>

<h2 id="default-application">Default application</h2>

<p>xdg-open</p>

<p>xdg-open is a desktop-independent tool for configuring default applications.</p>

<h2 id="daemons">Daemons</h2>

<p>Can stay in rc.conf
Alternatively, you may remove the /etc/rc.conf file entirely and enable services in systemd (see wiki).</p>

<h2 id="kernel-modules">Kernel modules</h2>

<p>Tip: Normally all needed modules are automatically loaded by udev, so you will rarely need to add something here. Only add modules that you know are missing.</p>

<p>Edit /etc/modules-load.d/ to configure kernel modules to load during boot in a static list. Each configuration file is named in the style of /etc/modules-load.d/<program>.conf. The configuration files should simply contain a list of kernel module names to load, separated by newlines. Empty lines and lines whose first non-whitespace character is # or ; are ignored. Example:</p>

<p>/etc/modules-load.d/virtio-net.conf
    # Load virtio-net.ko at boot
    virtio-net</p>

<hr />

<p>Browser Profiles</p>

<p>One can easily mount browser profile(s) such as chromium, firefox, opera, etc. into RAM via tmpfs and also use rsync to keep them synced with HDD-based backups. In addition to the obvious speed enhancements, users will also save read/write cycles on their SSD by doing so.</p>

<p>The AUR contains several packages to automate this process, for example profile-sync-daemon.</p>

<hr />

<ul>
<li><p>the underlying device must be aligned
(if using partitions, be sure you have start of partition aligned, better use &ldquo;fdisk -u&rdquo; to calculate in sectors.
If not sure, align to 1M or even 4M offset, this will always fit:-) (fdisk from latest util-linux-ng should support automatic alignment)</p></li>

<li><p>be sure that lvm2 PV metadata (data start) is always aligned (see pvcreate &ndash;dataalignment parameter)
(latest lvm2 already have support for automatic data alignment if kernel exports proper alignment data)</p></li>

<li><p>for cryptetup/LUKS - use &ldquo;&ndash;align-payload&rdquo; parameter (default is alignment to 4k boundary, not enough for SSD).
Note that parameter is in 512 bytes sectors!</p></li>
</ul>

<p>e.g. you want to align to 4MB boundary ( = 8192 * 512 bytes), use</p>

<p>cryptsetup luksFormat &ndash;align-payload=8192 &hellip;</p>

<p>verify with cryptsetup luksDump (see Payload offset)</p>

<p>(I usually set lvm2 extent size to 4MB and aling LUKS the same, so the LUKS header takes exactly one extent.)</p>

<ul>
<li>and finally, you should optimize FS above that device stack</li>
</ul>

<p>(From the kernel point of view, there is no difference if you put lvm2 over LUKS or vice versa - both should work the same. Just configuration is different, I have some old slides describing
activation of volumes here <a href="http://mbroz.fedorapeople.org/talks/LinuxAlt2008-eng/">http://mbroz.fedorapeople.org/talks/LinuxAlt2008-eng/</a> )</p>

<ul>
<li><p>properly align partition (use sectors, not default: fdisk -u, or use parted)</p></li>

<li><p>align data on LUKS drive (e.g. cryptsetup luksFormat &hellip; &ndash;align-payload=8192 to align to 4MB)</p></li>

<li><p>pvcreate &ndash;dataalignment 4M to align PV to 4M offset, all LVs will be aligned automagically when created (option available in recent lvm2)</p></li>
</ul>

<hr />

<p><strong>FOLLOWING IS NOT UPDATED YET</strong></p>

<h2 id="add-initial-user">Add initial user</h2>

<pre><code>useradd -m -G users,audio,lp,optical,storage,video,wheel,power,network -s /bin/bash yourname
</code></pre>

<p>Next, add a password for your new user using</p>

<pre><code>passwd yourname
</code></pre>

<h2 id="build-mirrolist">Build mirrolist</h2>

<p>Build a mirrorlist using the rankmirrors script</p>

<p>/usr/bin/rankmirrors is a python script which will attempt to detect the mirrors which are closest to the installation machine based on the mirrors specified in /etc/pacman.d/mirrorlist. Faster mirrors will dramatically improve pacman performance, and the overall Arch Linux experience. This script may be run periodically, especially if the chosen mirrors provide inconsistent throughput and/or updates.</p>

<p>First, use pacman to install python &amp; curl :</p>

<pre><code>pacman -Sy python curl
</code></pre>

<p>cd to the /etc/pacman.d/ directory:</p>

<pre><code>cd /etc/pacman.d
</code></pre>

<p>Backup the existing /etc/pacman.d/mirrorlist:</p>

<pre><code>cp mirrorlist mirrorlist.backup
</code></pre>

<p>Edit mirrorlist.backup and uncomment all mirrors on the same continent or within geographical proximity to test with rankmirrors.</p>

<pre><code>nano mirrorlist.backup
</code></pre>

<p>Run the script against the mirrorlist.backup with the -n switch and redirect output to a new /etc/pacman.d/mirrorlist file:</p>

<pre><code>rankmirrors -n 6 mirrorlist.backup &gt; mirrorlist
</code></pre>

<p>-n 6: rank the 6 fastest mirrors&lt;</p>

<p>After creating/editing /etc/pacman.d/mirrorlist, (manually or by /usr/bin/rankmirrors) issue the following command:</p>

<pre><code>pacman -Syy
</code></pre>

<h2 id="install-a-logon-manager">Install a logon manager</h2>

<h3 id="option-1-slim">Option 1: SLIM</h3>

<p>SLiM is not a good option for starting Gnome. Besides tweakings required for accessing gnome-keyring (see below) it won&rsquo;t allow you to use gnome deskbar to shutdown or reboot the machine (lack of consolekit support).</p>

<h4 id="install-slim">Install SLiM</h4>

<pre><code>pacman -S slim
</code></pre>

<p>There are also additional themes packages:</p>

<pre><code>pacman -S slim-themes archlinux-themes-slim
</code></pre>

<h4 id="configure-theme">Configure theme</h4>

<pre><code>nano /etc/slim.conf
</code></pre>

<p>For exemple to enable the archlinux theme:</p>

<pre><code>#current_theme       default
current_theme       archlinux-simplyblack
</code></pre>

<p>To preview a theme, run:</p>

<pre><code>slim -p /usr/share/slim/themes/&lt;theme name&gt;
</code></pre>

<p>Simply type &ldquo;exit&rdquo; and press Enter to get out of the preview.</p>

<h4 id="enable-slim-at-boot">Enable SLiM at boot</h4>

<p>There are two ways to do that:
  - Via Daemon
  - Via Run-level (this is the one described below)</p>

<p>Modify default run-level by editing /etc/inittab and find the line that looks like this:</p>

<pre><code>id:3:initdefault:
</code></pre>

<p>Modify the &lsquo;3&rsquo; to &lsquo;5&rsquo; for X11:</p>

<pre><code>id:5:initdefault:
</code></pre>

<p>Add or uncomment if exsiting the following line to /etc/inittab:
    x:5:respawn:/usr/bin/slim &gt;&amp; /dev/null</p>

<p>How to start from command line rather than SLiM?</p>

<h4 id="grant-access-to-gnome-keyring">Grant access to Gnome keyring</h4>

<p>If you are using SLiM to launch a Gnome session and have trouble accessing your keyring, for example not being automatically authenticated on login, add the following lines to /etc/pam.d/slim</p>

<pre><code>auth        optional    pam_gnome_keyring.so
session     optional    pam_gnome_keyring.so    auto_start
</code></pre>

<p>You also need to modify and replace login_cmd in /etc/slim.conf:</p>

<pre><code>login_cmd exec ck-launch-session dbus-launch /bin/bash -login ~/.xinitrc %session &gt;~/.xsession-errors 2&gt;&amp;1
</code></pre>

<h3 id="option-2-gdm">Option 2: GDM</h3>

<h4 id="install-gdm">Install gdm</h4>

<p>It is aleady installed with Gnome</p>

<h2 id="install-a-graphical-network-manager">Install a graphical network manager</h2>

<h3 id="disable-default-network-manager">Disable default network manager</h3>

<p>Edit /etc/rc.conf as root:</p>

<pre><code>nano /etc/rc.conf
</code></pre>

<p>Disable (!) any devices in the INTERFACES array that you wish to manage with Wicd. For example:</p>

<pre><code>INTERFACES=(!eth0 !wlan0)

#NETWORKS=(main)
#Static IP example
#eth0=&quot;eth0 192.168.0.2 netmask 255.255.255.0 broadcast 192.168.0.255&quot;
eth0=&quot;dhcp&quot;
INTERFACES=(!eth0 !eth1)

# Routes to start at boot-up (in this order)
# Declare each route then list in ROUTES
#   - prefix an entry in ROUTES with a ! to disable it
#
gateway=&quot;default gw 192.168.0.1&quot;
ROUTES=(!gateway)
</code></pre>

<h3 id="option-1-wicd">Option 1: wicd</h3>

<p>If you don&rsquo;t use OpenVPN, CiscoVPN or 3G broadband connection then wicd offers the best choice (fast, both GUI and CLI interface). When using the above modes it is recommended to use Gnome network manager</p>

<pre><code>pacman -S wicd pacman -S hicolor-icon-theme gksu python-notify
</code></pre>

<p>DO NOT INSTALL notification-daemon!!!</p>

<p>Now, add wicd to the DAEMONS array (hal before wicd). The DAEMONS array should now look something like this:</p>

<pre><code>DAEMONS=(syslog-ng hal !network !dhcdbd !networkmanager wicd ...)
</code></pre>

<p>Disable (!) any other existing network management daemons in the DAEMONS array, including network, dhcdbd, and networkmanager.
Note: wicd uses dbus but as we have with hal in DAEMONS array the Hal daemon will automatically start dbus for you.</p>

<p>Save and close.</p>

<p>the Unix group that dbus allows to access wicd is subject to change, and may be different than network. Check which policy group is specified in /etc/dbus-1/system.d/wicd.conf, and add your user to that group.</p>

<p>Lastly, reboot your PC. Note: There is no need to reboot your computer after installing and configuring wicd. Arch != Windows so there&rsquo;s no need to reboot after installing some (trivial) stuff like wicd. Start /etc/rc.d/dbus (or hal) and /etc/rc.d/wicd. If you want your new group for a user to be active you can just logout and login.</p>

<p>How to bypass Gnome keyring for normal users connecting with wireless</p>

<p>It&rsquo;s super simple! First, create a group called networkmanager with the following command (or any other method you prefer):</p>

<pre><code># groupadd networkmanager
</code></pre>

<p>Then add your user to that group using the following command (or any other preferred method):</p>

<pre><code># gpasswd -a username networkmanager
</code></pre>

<p>Replace username in the above command with your actual username.</p>

<p>Now, as root, launch nm-connection-editor and configure the connections:</p>

<pre><code># nm-connection-editor
</code></pre>

<p>Put a check mark next to &ldquo;Available to all users&rdquo; and apply the settings.
Note: on gnome3 you can just clik on Wireless settings, it will probably ask for password to run with root privileges.</p>

<p>Now you won&rsquo;t be bothered by Gnome keyring! (citation needed) Also, if you additionally enable &ldquo;connect automatically&rdquo;, your connection will be available and connected before you even log in to your desktop, making your whole startup process even faster!</p>

<p>ADDED SLIM with autologin!</p>

<p>modified /etc/slim.conf
    login_cmd           exec /bin/bash -login ~/.xinitrc %session
    auto_login          yes</p>

<p>modified .xinitrc
    exec ck-launch-session dbus-launch gnome-session</p>

<p>for intel graphic cards
edit /etc/mkinitcpio.conf</p>

<p>MODULES=&ldquo;i915&rdquo;</p>

<hr />

<p>+++ Backup keys</p>

<pre><code>dmsetup table --showkey

cryptsetup luksDump /dev/sda3 | grep &quot;Payload offset&quot;
</code></pre>

<p>Note Payload offset:    4040</p>

<p>then</p>

<pre><code>dd if=/dev/sda3 of=./backup.img bs=512 count=4040

dmsetup info -c
</code></pre>

<p>How do I backup a LUKS header?</p>

<p>While you could just copy the appropriate number of bytes from the start of the LUKS partition, the best way is to use command option &ldquo;luksHeaderBackup&rdquo; of cryptsetup. This protects also against errors when non-standard parameters have been used in LUKS partition creation. Example:</p>

<pre><code>     cryptsetup luksHeaderBackup --header-backup-file h /dev/mapper/c1
     cryptsetup luksHeaderBackup --header-backup-file h /dev/sda3
</code></pre>

<p>To restore, use the inverse command, i.e.</p>

<pre><code>     cryptsetup luksHeaderRestore --header-backup-file h /dev/mapper/c1
</code></pre>

<p>LVM header backup
         vgcfgbackup -f x201-lvm vgroup</p>

<p>+++ Restore keys</p>

<p>If you have live mapping still, you are not lost completely yet.
Do not reboot! First run &ldquo;dmsetup table &ndash;showkeys&rdquo; and &ldquo;dmsetup info -c&rdquo;
and store the full mapping to some file.</p>

<p>If you see dm-crypt mapping there mapped to proper drive, you can still recreate
LUKS header with some some magic.</p>

<p>(If you have saved that dmsetup mapping, I&rsquo;ll describe hot to save you data
- still depends how many of fs was overwritten.)</p>

<p>If you want help with that, paste here &ldquo;dmsetup table&rdquo; (<em>without</em> using &ndash;showkeys,
we do not want see your master key:-). For recovery you will need to know that key,
so be sure you have full table with key stored as written above.</p>

<p>(Table is created according to LUKS header which is lost, so after reboot you are
lost completely. BTW Passphrase will not help here at all.)
<a href="http://www.spinics.net/lists/dm-crypt/msg02914.html">http://www.spinics.net/lists/dm-crypt/msg02914.html</a>
<a href="https://code.google.com/p/cryptsetup/wiki/FrequentlyAskedQuestions#6._Backup_and_Data_Recovery">https://code.google.com/p/cryptsetup/wiki/FrequentlyAskedQuestions#6._Backup_and_Data_Recovery</a></p>

<p>UUID
<a href="http://www.datadisk.co.uk/html_docs/redhat/rh_lvm.htm">http://www.datadisk.co.uk/html_docs/redhat/rh_lvm.htm</a>
<a href="https://www.centos.org/docs/5/html/Cluster_Logical_Volume_Manager/mdatarecover.html">https://www.centos.org/docs/5/html/Cluster_Logical_Volume_Manager/mdatarecover.html</a></p>

<p>p
dd if=./backup.img of=/dev/sda3 bs=512 count=4040</p>

<p>+++ Mount from recovery CD
- modprobe dm-crypt (not required)
- cryptsetup luksOpen /dev/sda3 mylvm
- vgscan
- vgchange -ay
- mkdir /mnt/oldroot
- mount /dev/mapper/vgroup-root /mnt/oldroot</p>

<p>+++ fsck on lvm
fsck on lvm can be a bit tricky. Like a the normal process, the partition needs to be umounted and we can boot up using the rescue cd or in emergency mode. Normally, you fsck /dev/sda1</p>

<p>if the partition is lvm, you need to activate the lvm first like so</p>

<p>vgchange &ndash;ignorelockingfailure -ay
lvscan &ndash;ignorelockingfailure (this command should now work)
fsck /dev/volumegroup/lvname</p>

<p>if the logical volume contains a partition, you need to kpartx the lv.</p>

<p>+++ LVM snapshot</p>

<p><a href="http://www.thegoldfish.org/2011/09/reverting-to-a-previous-snapshot-using-linux-lvm/">http://www.thegoldfish.org/2011/09/reverting-to-a-previous-snapshot-using-linux-lvm/</a>
<a href="http://www.redhatlinux.info/2010/11/lvm-logical-volume-manager.html">http://www.redhatlinux.info/2010/11/lvm-logical-volume-manager.html</a>
<a href="http://doc.ubuntu-fr.org/lvm">http://doc.ubuntu-fr.org/lvm</a></p>

<p>LVM snapshot</p>

<p>lvcreate -L 10g -s -n mysnapshot /dev/vgroup/root</p>

<p>Revert back to LVM snapshot</p>

<p>Reboot with USB Archlinu key
- loadkeys fr
- cryptsetup luksOpen /dev/sda4 mylvm
- vgscan
- vgchange -ay
- lvconvert &ndash;merge /dev/vgroup/mysnapshot
- reboot for root partition</p>

<p>then for non root
umount /home
lvchange -an vgroup/home
dmsetup status vgroup-snaphome
lvchange -ay vgroup/home</p>

<p>remove snapshot</p>

<h1 id="umount-dev-vgroup-mysnapshot">umount /dev/vgroup/mysnapshot</h1>

<h1 id="lvremove-dev-vgrou-mysnapshot">lvremove /dev/vgrou/mysnapshot</h1>

<hr />

<p>++ Manual Luks volume</p>

<p>dd if=/dev/zero of=/bigsecret bs=1M count=10
losetup /dev/loop0 /bigsecret
cryptsetup luksFormat /dev/loop0
===&gt; cryptsetup luksFormat -c cast5-cbc-plain -s 128 -h sha256 /dev/$DEVICE
cryptsetup luksOpen /dev/loop0 secret</p>

<p>FORMAT
mkfs.ext2 /dev/mapper/secret</p>

<p>MOUNT
mkdir /mnt/secret
mount -t ext2 /dev/mapper/secret /mnt/secret</p>

<p>UMOUNT
umount /mnt/secret
cryptsetup luksClose secret
losetup -d /dev/loop0 # free the loopdevice.</p>

<p>REMOUNT
losetup /dev/loop0 /bigsecret
cryptsetup luksOpen /dev/loop0 secret
mount -t ext2 /dev/mapper/secret /mnt/secret</p>

<p>check if trim is enabled
<a href="https://sites.google.com/site/lightrush/random-1/checkiftrimonext4isenabledandworking">https://sites.google.com/site/lightrush/random-1/checkiftrimonext4isenabledandworking</a></p>

<h2 id="optimization">Optimization</h2>

<p>optimization
<a href="http://postblue.info/netbook-archlinux-i3-optimisation/">http://postblue.info/netbook-archlinux-i3-optimisation/</a></p>

<p>power saving
<a href="https://github.com/Unia/powersave">https://github.com/Unia/powersave</a>
<a href="http://crunchbang.org/forums/viewtopic.php?id=11954&amp;p=1">http://crunchbang.org/forums/viewtopic.php?id=11954&amp;p=1</a></p>

<p>nice example from postblue
<a href="http://bin.postblue.info/powersave">http://bin.postblue.info/powersave</a></p>

<h3 id="forcer-aspm-powersave-par-un-argument-dans-grub">Forcer ASPM powersave par un argument dans GRUB ;</h3>

<p>Insérez pcie_aspm=force dans /etc/default/grub à la ligne GRUB_CMDLINE_LINUX, puis régénérez GRUB2 d’un grub-mkconfig -o /boot/grub/grub.cfg.</p>

<h2 id="change-what-systemd-can-control">Change what systemd can control</h2>

<p>permettre à systemd de gérer les événements du matériel en éditant le fichier /etc/systemd/logind.conf ;</p>

<h2 id="enable-governors">Enable governors</h2>

<pre><code>créer le fichier /etc/modules-load.d/cpufreq.conf afin d’activer les modules de contrôle de la fréquence du processeur, avec le contenu suivant ; ici j’utilise le module acpi_cpufreq mais choisissez le module qui convient le mieux à votre matériel :

# Load cpufreq driver
acpi_cpufreq
# Load cpufreq governors
cpufreq_performance
cpufreq_powersave
cpufreq_ondemand
</code></pre>

<h2 id="powersave">Powersave</h2>

<p>/etc/udev/rules.d/50-powersave.rules
    SUBSYSTEM==&ldquo;power_supply&rdquo;, ENV{POWER_SUPPLY_ONLINE}==&ldquo;0&rdquo;, RUN+=&ldquo;/usr/bin/powersave true&rdquo;
    SUBSYSTEM==&ldquo;power_supply&rdquo;, ENV{POWER_SUPPLY_ONLINE}==&ldquo;1&rdquo;, RUN+=&ldquo;/usr/bin/powersave false&rdquo;
    KERNEL==&ldquo;sr0&rdquo;, SUBSYSTEM==&ldquo;block&rdquo;, ENV{POWER_SUPPLY_ONLINE}==&ldquo;0&rdquo;, ENV{UDISKS_DISABLE_POLLING}=&ldquo;1&rdquo;
    KERNEL==&ldquo;sr0&rdquo;, SUBSYSTEM==&ldquo;block&rdquo;, ENV{POWER_SUPPLY_ONLINE}==&ldquo;1&rdquo;, ENV{UDISKS_DISABLE_POLLING}=&ldquo;0&rdquo;</p>

<p>/usr/lib/systemd/system-sleep/powersave.sh</p>

<pre><code>#!/bin/sh

case $1 in
    pre) /usr/bin/powersave false ;;
        post)
    if cat /sys/class/power_supply/ADP1/online | grep 0 &gt; /dev/null 2&gt;&amp;1
        then
             /usr/bin/powersave true
        else
             /usr/bin/powersave false
        fi
    ;;
esac
exit 0
</code></pre>

<p>Change execution flag</p>

<pre><code># chmod +x /usr/lib/systemd/system-sleep/powersave.sh
</code></pre>

<p>/usr/bin/powersave
#!/bin/sh</p>

<p>case &ldquo;$1&rdquo; in
    true) # Enable power saving settings on battery
      # bus
      for i in /sys/bus/<em>/devices/</em>/power/control; do echo auto &gt; $i; done
      # usb autosuspend
      for i in /sys/bus/usb/devices/<em>/power/autosuspend; do echo 1 &gt; $i; done
      for i in /sys/bus/usb/devices/</em>/power/control; do echo auto &gt; $i; done
          # sata powersave
          for i in /sys/class/scsi_host/host<em>/link_power_management_policy; do echo min_power &gt; $i; done
          # disk powersave
          #for dev in /dev/sd[a-z]; do hdparm -S 12 -B 200 -a 2048 $dev; done
      # nmi_watchdog
      echo 0 &gt; /proc/sys/kernel/nmi_watchdog
      # cpu
      for i in /sys/devices/system/cpu/cpu</em>/cpufreq/scaling_governor; do echo powersave &gt; $i; done
          #echo 1 &gt; /sys/devices/system/cpu/sched_smt_power_savings
          #echo 1 &gt; /sys/devices/system/cpu/sched_mc_power_savings
      #echo 80 &gt; /sys/devices/system/cpu/cpufreq/conservative/up_threshold
          #echo 40 &gt; /sys/devices/system/cpu/cpufreq/conservative/down_threshold
          #echo 20000 &gt; /sys/devices/system/cpu/cpufreq/conservative/sampling_rate
          #echo 1 &gt; /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
          #echo 20 &gt; /sys/devices/system/cpu/cpufreq/conservative/freq_step
          # aspm
      echo powersave &gt; /sys/module/pcie_aspm/parameters/policy
      # kernel write mode
      echo 5 &gt; /proc/sys/vm/laptop_mode
      echo 90 &gt; /proc/sys/vm/dirty_ratio
      echo 1 &gt; /proc/sys/vm/dirty_background_ratio
      echo 1500 &gt; /proc/sys/vm/dirty_expire_centisecs
      echo 1500 &gt; /proc/sys/vm/dirty_writeback_centisecs
      # sound card powersave
      echo 1 &gt; /sys/module/snd_hda_intel/parameters/power_save
      echo Y &gt; /sys/module/snd_hda_intel/parameters/power_save_controller
          #echo 1 &gt; sys/module/snd_ac97_codec/parameters/power_save
      # wlan0/eth0 powersave
      iwconfig wlan0 power on
          ethtool -s eth0 wol d
          # i915
          echo 1 &gt; /sys/module/i915/parameters/i915_enable_rc6
          echo 1 &gt; /sys/module/i915/parameters/i915_enable_fbc
          echo 1 &gt; /sys/module/i915/parameters/powersave
          echo 1 &gt; /sys/module/i915/parameters/semaphores
          echo 1 &gt; /sys/module/i915/parameters/lvds_downclock
      ;;
    false) # Return to default on AC power
      # bus
      for i in /sys/bus/<em>/devices/</em>/power/control; do echo on &gt; $i; done
      # usb autosuspend
      for i in /sys/bus/usb/devices/<em>/power/autosuspend; do echo 0 &gt; $i; done
      for i in /sys/bus/usb/devices/</em>/power/control; do echo on &gt; $i; done
          # sata powersave
      for i in /sys/class/scsi_host/host<em>/link_power_management_policy; do echo max_performance &gt; $i; done
          # disk powersave rotational only
          #for dev in /dev/sd[a-z]; do hdparm -S 120 -B 255 -a 128 $dev; done
      # nmi_watchdog
      echo 1 &gt; /proc/sys/kernel/nmi_watchdog
      # cpu
      for i in /sys/devices/system/cpu/cpu</em>/cpufreq/scaling_governor; do echo performance &gt; $i; done
          #echo 0 &gt; /sys/devices/system/cpu/sched_smt_power_savings
          #echo 0 &gt; /sys/devices/system/cpu/sched_mc_power_savings
      # aspm
      echo performance &gt; /sys/module/pcie_aspm/parameters/policy
      # kernel write mode
      echo 0 &gt; /proc/sys/vm/laptop_mode
      echo 10 &gt; /proc/sys/vm/dirty_ratio
      echo 5 &gt; /proc/sys/vm/dirty_background_ratio
      echo 500 &gt; /proc/sys/vm/dirty_expire_centisecs
      echo 500 &gt; /proc/sys/vm/dirty_writeback_centisecs
      # sound card powersave
      echo 0 &gt; /sys/module/snd_hda_intel/parameters/power_save
      echo Y &gt; /sys/module/snd_hda_intel/parameters/power_save_controller
          #echo 0 &gt; sys/module/snd_ac97_codec/parameters/power_save
      # wlan0/eth0 powersave
          iwconfig wlan0 power off
          ethtool -s eth0 wol d
          # i915
          echo 0 &gt; /sys/module/i915/parameters/i915_enable_rc6
          echo 0 &gt; /sys/module/i915/parameters/i915_enable_fbc
          echo 0 &gt; /sys/module/i915/parameters/powersave
          echo 0 &gt; /sys/module/i915/parameters/semaphores
          echo 0 &gt; /sys/module/i915/parameters/lvds_downclock
      ;;
esac
exit 0</p>

<p>chmod +x /usr/bin/powersave</p>

<p>disabled for now
echo 1 &gt; /sys/module/snd_hda_intel/parameters/power_save
      echo Y &gt; /sys/module/snd_hda_intel/parameters/power_save_controller
          #echo 1 &gt; sys/module/snd_ac97_codec/parameters/power_save</p>

<p>xdg-user-dirs uses a configuration file located at ~/.config/user-dirs.dir. Its format is as follows</p>

<pre><code>## Localized folders

# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR=&quot;$HOME/yyy&quot;, where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR=&quot;/yyy&quot;, where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR=&quot;$HOME/Bureau&quot;
XDG_DOWNLOAD_DIR=&quot;$HOME/Téléchargements&quot;
XDG_TEMPLATES_DIR=&quot;$HOME/Modèles&quot;
XDG_PUBLICSHARE_DIR=&quot;$HOME/Public&quot;
XDG_DOCUMENTS_DIR=&quot;$HOME/Documents&quot;
XDG_MUSIC_DIR=&quot;$HOME/Musique&quot;
XDG_PICTURES_DIR=&quot;$HOME/Images&quot;
XDG_VIDEOS_DIR=&quot;$HOME/Vidéos&quot;
</code></pre>

<p>Remove or rename the one you like/don&rsquo;t like and also delete the folders from the drives for the one you no longer want.</p>

<h2 id="remove-guake-title">Remove guake title</h2>

<pre><code># gconf-editor


/apps/guake/general/use_vte_titles 
</code></pre>

<h2 id="fix-nautilus-sort">Fix Nautilus sort</h2>

<p><a href="http://www.subdude-site.com/WebPages_Local/RefInfo/Computer/Linux/LinuxGuidesByBlaze/Nautilus_Guide/NautilusGuideBlaze.htm#grp_NautilusSort">http://www.subdude-site.com/WebPages_Local/RefInfo/Computer/Linux/LinuxGuidesByBlaze/Nautilus_Guide/NautilusGuideBlaze.htm#grp_NautilusSort</a></p>

<p>Create/Edit ~/.gnomerc</p>

<p>and add</p>

<pre><code>#export LC_COLLATE=C  That was the original post
</code></pre>

<p>replaced by</p>

<pre><code>#export LC_COLLATE=&quot;fr_FR.UTF-8&quot;
</code></pre>

<p>IMPORTANT NOTE: You must make the &lsquo;.gnomerc&rsquo; file executable before restarting your computer. You can use a command like</p>

<p>chmod 755 .gnomerc
      or
chmod 700 .gnomerc</p>

<p><a href="https://bbs.archlinux.org/viewtopic.php?pid=1081952">https://bbs.archlinux.org/viewtopic.php?pid=1081952</a></p>

<p>In the end I got it working with:
/etc/locale.conf</p>

<pre><code>LANG=fr_FR.UTF-8
#LC_COLLATE=&quot;C&quot;
LC_COLLATE=&quot;fr_FR.UTF-8&quot;
</code></pre>

<p>and adding/modifying the following in  ~/.zshrc.local</p>

<pre><code>export LC_ALL=&quot;fr_FR.UTF-8&quot;
#export LC_COLLATE=&quot;C&quot;
export LC_COLLATE=&quot;fr_FR.UTF-8&quot;
</code></pre>

<h2 id="cups-1">CUPS</h2>

<pre><code># systemctl enable cups.service
</code></pre>

<h2 id="cups-pdf">CUPS PDF</h2>

<p>PDF virtual printer</p>

<p>CUPS-PDF is a nice package that allows one to setup a virtual printer that will generate a PDF from anything sent to it. Obviously this package is not necessary, but it can be quite useful.</p>

<p>Find generated PDF documents in a sub-directory located at /var/spool/cups-pdf. Normally, the subdirectory is named after the user who performed the job. A little tweak helps you to find your printed PDF documents more easily. Edit /etc/cups/cups-pdf.conf by changing the line</p>

<pre><code>#Out /var/spool/cups-pdf/${USER}

    to

Out /home/${USER}

This package can be installed by the following command: 

pacman -S cups-pdf
</code></pre>

<p>After installing the package, set it up as if it were for any other printer by using the web interface. For the Device, select CUPS-PDF (Virtual PDF Printer); Make/Manufacturer, choose Generic; Model/Driver, select Generic postscript color printer or Generic Cups-PDF Printer.</p>

<p>Quality sucks!</p>

<h2 id="cron">Cron</h2>

<p>Not enabled by default</p>

<pre><code># systemctl enable cronie.service
</code></pre>

<h2 id="journal">Journal</h2>

<p>Since version 38, systemd has its own logging system, the journal. Therefore, running a syslog daemon is no longer required. To read the log, use:</p>

<pre><code># journalctl
</code></pre>

<p>By default (when Storage= is set to auto in /etc/systemd/journald.conf), the journal writes to /var/log/journal/. If the directory /var/log/journal/ does not exist (e.g. if you or some program delete it), systemd will not create it automatically, but instead write its logs to /run/systemd/journal. This means that logs will be lost on reboot.</p>

<p>On default installation it appears to be using /var/log/journal</p>

<h2 id="disable-ipv6">Disable IPV6</h2>

<p>Adding ipv6.disable=1 to the kernel line disables the whole IPv6 stack, which is likely what you want if you are experiencing issues. See Kernel parameters for more information.</p>

<h2 id="crpyptostick-gnome">Crpyptostick &amp; Gnome</h2>

<ul>
<li><p>Disabled gnome-keyring in gnome-session-properties</p></li>

<li><p>disable gpg-agent in ~/.gnupg.conf</p></li>

<li><p>create /etc/profile.d/gpg-agent.sh</p>

<p>#!/bin/sh</p>

<p>envfile=&ldquo;${HOME}/.gnupg/gpg-agent.env&rdquo;
if test -f &ldquo;$envfile&rdquo; &amp;&amp; kill -0 $(grep GPG_AGENT_INFO &ldquo;$envfile&rdquo; | cut -d: -f 2) 2&gt;/dev/null; then
    eval &ldquo;$(cat &ldquo;$envfile&rdquo;)&rdquo;
    else
eval &ldquo;$(gpg-agent &ndash;daemon &ndash;write-env-file &ldquo;$envfile&rdquo;)&rdquo;</p>

<h1 id="eval-gpg-agent-daemon-enable-ssh-support-write-env-file-envfile">eval &ldquo;$(gpg-agent &ndash;daemon &ndash;enable-ssh-support &ndash;write-env-file &ldquo;$envfile&rdquo;)&rdquo;</h1>

<p>fi
export GPG_AGENT_INFO  # the env file does not contain the export statement</p></li>
</ul>

<p>chmod + x /etc/profile/d/gpg-agent.sh</p>

<ul>
<li><p>create /etc/udev/rules.d/40-cryptostick.rules</p>

<h1 id="do-not-edit-this-file-it-will-be-overwritten-on-update">do not edit this file, it will be overwritten on update</h1>

<p>SUBSYSTEM!=&ldquo;usb&rdquo;, GOTO=&ldquo;cryptostick_rules_end&rdquo;
ACTION!=&ldquo;add&rdquo;, GOTO=&ldquo;cryptostick_rules_end&rdquo;</p>

<p>ATTR{idVendor}==&ldquo;20a0&rdquo;, ATTR{idProduct}==&ldquo;4107&rdquo;, ENV{ID_SMARTCARD_READER}=&ldquo;1&rdquo;, ENV{ID_SMARTCARD_READER_DRIVER}=&ldquo;gnupg&rdquo;</p>

<p>LABEL=&ldquo;cryptostick_rules_end&rdquo;</p></li>
</ul>

<h2 id="maxim-vpn">Maxim VPN</h2>

<p>/etc/systemd/system/ciscovpn.service</p>

<pre><code>[Unit]
Description=Cisco AnyConnect Secure Mobility Client Agent
Requires=network.target remote-fs.target
After=network.target remote-fs.target

[Service]
Type=forking
PIDFile=/var/run/vpnagentd.pid
ExecStart=/opt/cisco/vpn/bin/vpnagentd
ExecStop=/usr/bin/killall /opt/cisco/vpn/bin/vpnagentd
Restart=on-abort

[Install]
# one may want to use multi-user.target instead
WantedBy=graphical.target


## Some systemd services
https://wiki.archlinux.org/index.php/Systemd/Services
</code></pre>

<p>sudo lvcreate -L 2g -s -n home-snapshot /dev/vgroup/home
sudo lvcreate -L 2g -s -n root-snapshot /dev/vgroup/root
sudo cp /boot/vmlinuz-linux /boot/vmlinuz-linux-PREVIOUS
sudo cp /boot/vmlinuz-linux-ck /boot/vmlinuz-linux-ck-PREVIOUS
sudo cp /boot/initramfs-linux.img /boot/initramfs-linux-PREVIOUS.img
sudo cp /boot/initramfs-linux-ck.img /boot/initramfs-linux-ck-PREVIOUS.img</p>

<p>if everything is ok, remove snapshots:
sudo lvremove /dev/vgroup/root-snapshot
sudo lvremove /dev/vgroup/home-snapshot</p>

<p>issues with i915</p>

<p>removed echo 0 &gt; /sys/module/i915/parameters/i915_enable_rc6
          echo 0 &gt; /sys/module/i915/parameters/i915_enable_fbc
          echo 0 &gt; /sys/module/i915/parameters/powersave</p>

<p>from /usr/bin/powersave</p>

<p>Added i915 in /etc/mkinitcpio.conf
Created /etc/modprobe.d/i915.conf</p>

<p>options i915 i915_enable_rc6=1
options i915 i915_enable_fbc=1
options i915 lvds_downclock=1</p>

<p>Removed from grub default</p>

<p>apparement si i915 est dans mkinitcpio.conf alors on ne peut plus l&rsquo;écrire après, uniquement via i915.conf (a investiguer)</p>

            </div>
            <footer class="article-footer">
    <a data-url="https://danynativel.com/2013/02/10/archlinux-installation-guide-on-encrypted-ssd" data-id="19d0ddf6225463f44698550443dccc42" class="article-share-link">
        Share
    </a>
    
</footer>

        </div>

        
<nav id="article-nav">
    
    <a href="https://danynativel.com/2012/08/09/clone-mifare-cards-using-chinesse-uuid-writable-cards" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">
          Older
      </strong>
      <div class="article-nav-title">Clone MiFare cards using Chinesse UUID writable cards</div>
    </a>
    

    
    <a href="https://danynativel.com/2013/02/11/sold-my-x100" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">
          Newer
      </strong>
      <div class="article-nav-title">Sold my X100...Waiting for the X100S</div>
    </a>
    
</nav>


    </article>

    
    <section id="comments">
        <div id="disqus_thread">
            
        </div>
    </section>
    
</section>


	    
	    <aside id="sidebar">
    

    


<div class="widget-wrap">
    <h3 class="widget-title">Categories</h3>
    <div class="widget">
        <ul class="category-list">
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/categories/computer">
                    computer
                </a>
                <span class="category-list-count">11</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/categories/freediving">
                    freediving
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/categories/photography">
                    photography
                </a>
                <span class="category-list-count">5</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/categories/videography">
                    videography
                </a>
                <span class="category-list-count">1</span>
            </li>
            
        </ul>
    </div>
</div>



    


<div class="widget-wrap">
    <h3 class="widget-title">
        Tags
    </h3>
    <div class="widget">
        <ul class="category-list">
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/apple">
                    apple
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/archlinux">
                    archlinux
                </a>
                <span class="category-list-count">5</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/competition">
                    competition
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/dance">
                    dance
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/hacking">
                    hacking
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/hardware">
                    hardware
                </a>
                <span class="category-list-count">2</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/how-to">
                    how-to
                </a>
                <span class="category-list-count">10</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/linux">
                    linux
                </a>
                <span class="category-list-count">9</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/music">
                    music
                </a>
                <span class="category-list-count">2</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/photos">
                    photos
                </a>
                <span class="category-list-count">2</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/review">
                    review
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/security">
                    security
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/tips">
                    tips
                </a>
                <span class="category-list-count">1</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/unraid">
                    unraid
                </a>
                <span class="category-list-count">5</span>
            </li>
            
            <li class="category-list-item">
                <a class="category-list-link" href="https://danynativel.com/tags/videos">
                    videos
                </a>
                <span class="category-list-count">1</span>
            </li>
            
        </ul>
    </div>
</div>



    


<div class="widget-wrap">
    <h3 class="widget-title">
        Tag cloud
    </h3>
    <div class="widget tagcloud">
        
        <a href="https://danynativel.com/tags/apple" style="font-size: 12px;">apple</a>
        
        <a href="https://danynativel.com/tags/archlinux" style="font-size: 12px;">archlinux</a>
        
        <a href="https://danynativel.com/tags/competition" style="font-size: 12px;">competition</a>
        
        <a href="https://danynativel.com/tags/dance" style="font-size: 12px;">dance</a>
        
        <a href="https://danynativel.com/tags/hacking" style="font-size: 12px;">hacking</a>
        
        <a href="https://danynativel.com/tags/hardware" style="font-size: 12px;">hardware</a>
        
        <a href="https://danynativel.com/tags/how-to" style="font-size: 12px;">how-to</a>
        
        <a href="https://danynativel.com/tags/linux" style="font-size: 12px;">linux</a>
        
        <a href="https://danynativel.com/tags/music" style="font-size: 12px;">music</a>
        
        <a href="https://danynativel.com/tags/photos" style="font-size: 12px;">photos</a>
        
        <a href="https://danynativel.com/tags/review" style="font-size: 12px;">review</a>
        
        <a href="https://danynativel.com/tags/security" style="font-size: 12px;">security</a>
        
        <a href="https://danynativel.com/tags/tips" style="font-size: 12px;">tips</a>
        
        <a href="https://danynativel.com/tags/unraid" style="font-size: 12px;">unraid</a>
        
        <a href="https://danynativel.com/tags/videos" style="font-size: 12px;">videos</a>
        
    </div>
</div>




    <div id="toTop" class="fa fa-chevron-up"></div>
</aside>

	    
	</div>
</div>

<footer id="footer">
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2016
      Powered by <a href="//gohugo.io">Hugo</a>. Theme by <a href="http://github.com/ppoffice">PPOffice</a>.
    </div>
  </div>
</footer>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://danynativel.com/fancybox/jquery.fancybox.pack.js"></script>
<script src="https://danynativel.com/js/script.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<!-- MathJax -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']]}
  });
</script>
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

</body>
</html>
